# Generated by Django 3.2.25 on 2024-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='img/logo.png', upload_to='img/'),
        ),
    ]
